name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web_model:latest

      - name: Run tests
        run: |
          docker-compose up -d
          docker-compose exec web npm test
          docker-compose down

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          action: deploy
          images: ${{ secrets.DOCKER_USERNAME }}/web_model:latest
          namespace: default
          manifests: |
            ./k8s/deployment.yaml
            ./k8s/service.yaml

      - name: Build and push .NET Aspire service image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dotnet_aspire:latest

      - name: Deploy .NET Aspire service to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          action: deploy
          images: ${{ secrets.DOCKER_USERNAME }}/dotnet_aspire:latest
          namespace: default
          manifests: |
            ./k8s/aspire-deployment.yaml
            ./k8s/aspire-service.yaml
